services:
  backendospaye:
    # nombre del servicio en min√∫sculas para evitar problemas
    build: ./backendpasantias
    image: backendospaye:latest
    mem_limit: 512m
    ports:
      - "9000:9000"
    environment:
      DB_URL: jdbc:mysql://ospuaye:3306/backendospuaye?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      ospuaye:
        condition: service_healthy

  ospuaye:
    image: mysql:9.2.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: backendospuaye
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
