services:
  backendospaye:
    build: ./backendOspuaye
    image: backendospaye:latest
    mem_limit: 512m
    ports:
      - "9000:9000"
    environment:
      DB_URL: jdbc:mysql://ospuaye:3306/backendospuaye
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      ospuaye:
        condition: service_healthy

  ospuaye:
    image: mysql:8.0
    container_name: mysql_ospuaye
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: backendospuaye
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
